### ISSUE TITLE
Feature Request: Allow for larger than 100x100 projects

### ISSUE THREAD

**Issue by d4rk22** [dcarubia/easy-floorplan#2]
I really love this tool but I can't quite fit half of my house into it at a 4" resolution that would allow it to match up exactly. Would be awesome if you could go larger with projects even if it's not enabled by default. 150x150 or 200x200 would do it.

**Comment by dcarubia** [comment]
In the official release, which I'm hoping will be out by mid-November, the document size will be at least 160x260. There will also be zoom functionality which will allow you to view your whole house without scrolling. Let me know if you have any other thoughts regarding the document size.

**Comment by d4rk22** [comment]
That should be plenty big enough. Feel free to close this issue.
